# Generated by Django 4.0.3 on 2022-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('latin_name', models.CharField(max_length=255)),
                ('sow_indoors_earliest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sow_indoors_latest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('transplant_earliest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('transplant_latest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sow_outdoors_earliest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sow_outdoors_latest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('harvest_earliest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('harvest_latest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
